export enum ECategory {
    Electronics = 'Electronics',
    Furniture = 'Furniture',
    Fashion = 'Fashion',
    Sports = 'Sports',
    KitchenAppliances = 'Kitchen Appliances',
    HomeAppliances = 'Home Appliances',
    ToysAngGames = "Toys & Games",
    Gardening = 'Gardening',
    Fitness = 'Fitness',
    Footwear = 'Footwear',
    ComputerAccessories = 'Computer Accessories',
    PersonaCare = "Personal Care",
    OutdoorGear = 'Outdoor Gear',
    OfficeSupplies = 'Office Supplies',
    BedsAndLuggage = 'Bags & Luggage',
    HomeSecurity = 'Home Security',
    Other = 'Other',

}
